# Generated by Django 2.0.1 on 2018-01-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100)),
                ('price_book', models.IntegerField(default=36)),
            ],
        ),
        migrations.CreateModel(
            name='teacherBMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_fio', models.CharField(max_length=100)),
                ('teacher_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacherIU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_fio', models.CharField(max_length=100)),
                ('teacher_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacherRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_fio', models.CharField(max_length=100)),
                ('teacher_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacherSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_fio', models.CharField(max_length=100)),
                ('teacher_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_fio', models.CharField(max_length=100)),
                ('writer_book', models.CharField(max_length=100)),
            ],
        ),
    ]
