# Generated by Django 2.0.1 on 2018-01-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheriu',
            name='teacher_f',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
