# Generated by Django 2.0.1 on 2018-01-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_teacheriu_teacher_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id_groups', models.AutoField(primary_key=True, serialize=False)),
                ('group_number', models.CharField(max_length=45, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id_students', models.AutoField(primary_key=True, serialize=False)),
                ('student_fio', models.CharField(max_length=100, verbose_name='ФИО Студента')),
                ('group_number', models.CharField(max_length=100, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_fio', models.CharField(max_length=100, verbose_name='ФИО преподавателя')),
                ('teacher_department', models.CharField(max_length=100, verbose_name='Кафедра')),
                ('group_num', models.ManyToManyField(to='my_app.groups', verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.students', verbose_name='Факультет'),
        ),
    ]
